### ISSUE TITLE
Show toaster on config reload

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#3034]
**Describe the issue**
When using classloader.type=ScanningDirectoryClassLoader you need to check the status page to be sure that the config has been reloaded after you saved your config and before testing your change in the Frank!Console. When you are mainly using test a pipeline, Larva or Ladybug (or any other page in the console) while developing your adapter it would be nice to have a toaster message on that page saying the config has been (automatically) reloaded (a green message when ok and a red message when an error occurred) so you don't have to visit the status page before doing you next test after you changed your config.

**Reporter**
Jaco de Groot

**To Reproduce**
\-

**Screenshots**
\-

**Configuration**
\-

**Input**
\-

**Environment**
```
FF! 7.8-20220407.104516: Frank2Example4
Running on xxx using Apache Tomcat/9.0.60
Java Version: OpenJDK Runtime Environment (1.8.0_292-b10)
Heap size: 259M, total JVM memory: 614M
Free disk space: 84GB, total disk space: 475GB
Up since: 2022-04-07 17:43:01 (2h) 
```

**Additional Environment**
\-

**Additional Context**
\-

**Comment by jjansenvr** [comment]
impacts the performance and console because it needs polling for the reload.

**Comment by MLenterman** [comment]
Would like to see the toaster too!

**Comment by Matthbo** [comment]
With how to framework and console currently keep track of configuration and adapter changes it isn't an easy task to see when a reload has occurred.
Best I can do is check if the adapter uptime has changed, which it will have after its has stopped and started again, which means I need to check the difference on every adapter when it gets this information from the backend (currently requested every 3 seconds).

**Comment by philipsens** [comment]
I think it could be easier to have a different endpoint on the backend, specifically for these kinds of notifications. That would make it possible to show other useful messages from the backend.

**Comment by Matthbo** [comment]
Good idea, I had a quick conversation about this with Niels where we also talked about adding support for websocket communication as a modern alternative for poller.
However in this case it doesn't matter much since even the framework itself doesnt keep track of reloads, only the `STARTED`, `STARTING` & `STOPPED` states are being tracked.
So I still need to deduce somewhere that a configuration or adapter was reloaded between pollings.
At the moment I implemented it in such a way that I check the new `upSince` integer timestamp with the old one, if the new one is higher then a reload of some sort must have occurred
