### ISSUE TITLE
Liveness, Readiness and Startup probes for K8S

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#3867]
**Describe the issue**
There are multiple probes on which the k8s cluster can act such as the startup probe which disables the liveness and readiness probes until the application succeeds starting up.
Liveness probes are used to know when to restart a container.
Readiness probes are used to know when a container is ready to start accepting traffic.

See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ for more info.

**Reporter**
Sergi

**Comment by ricardovh** [comment]
Kubernetes can use HTTP calls to determine this, and our default health endpoint (/iaf/api/server/health) returns 200 OK when all adapters are started which can be used for these probes.

**Comment by philipsens** [comment]
> Kubernetes can use HTTP calls to determine this, and our default health endpoint (/iaf/api/server/health) returns 200 OK when all adapters are started which can be used for these probes.

Stopping an adapter will give back an error code, hard-restarting the pod (if used as liveness probe)

---

I want to add that it would be nice if the startup probe could determine if the migrations have run.

**Comment by philipsens** [comment]
I've had a discussion with @MLenterman about this, because he was having some issues. This sparked a new idea.

If the health endpoint could be split (or extended) into an endpoint for framework operations and an endpoint for adapter statuses, then we can create these scenarios: 
* Startup -> framework: Wait for connections and migrations (before accepting traffic)
* Liveness -> framework: Check if still running and connected to database (@MLenterman had an issue with not reconnecting if memory was low) 
* Readiness -> adapters: Check if able to accept traffic (and reroute traffic to other pod if adapters are reloading)

Manually stopping adapters should have no effect, which is an exception to the readiness probe. But it would be a better solution to disable an adapter with stage/side specifics anyway.
