### ISSUE TITLE
Healthcheck endpoint flexibility 

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#4114]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
The generic health check endpoint of the Frank is not flexible enough for container environments

As a developer you want to be able to have some flexibility on how and when you want a node to be restart

We need to have a refinement to determine the precise   
**possible settings:**
- manually stopping an adapter should not trigger a redeploy?
- jms could be treated differently than http traffic especially FF ?
- 

**Reporter**
jjansenvr

**To Reproduce**

**Screenshots**

**Configuration**
```
Please provide the configuration of the Pipe or Receiver with the problem.
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
Please go to the console of your Frank, click on 'Information' and copy-paste the results here. 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by Laurens-makel** [comment]
I was speaking to @nielsm5 today about this topic.

We would like to use FF health check instead of the one provided by WAS, although it does occur that we stop certain adapters at certain times. 

With the current implementation, the health check will fail in those situations and cause the loadbalancer to re-route all other traffic to the healthy nodes (if any left if adapter needs to be stopped on all nodes).

Same idea applies when a certain adapter fails, only traffic towards that adapter should be stopped but this issue is also related to the loadbalancer implementation..

It's a difficult topic considering that on k8s you'd prefer to run to small and isolated services and when required to stop certain adapters, you should be able to manage on k8s that the related deployment will be stopped. It might occur that in certain situtations you can't have this level of isolation and it still occurs that individual adapters might need to be stopped..

In a WAS situation, usually applications are more structured towards the classic monolith application. There are multiple services hosted on the same instance of the framework, if one service is unavailable, it should not cause all other services to go down.

Ideally a service level health check is provided by the framework, depending on the loadbalancer used, it might solve the problem. Another idea is to create open source configurations for several loadbalancers to make service level health checks work..
