### ISSUE TITLE
server health endpoint is protected

### ISSUE THREAD

**Issue by VBPham** [frankframework/frankframework#5559]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
/api/server/health endpoint is protected and gives 403. Used to be not the case. My aws setup is relying on this endpoint to be public. I am using 7.9-20231011.232317

**Comment by alisihab** [comment]
This issue persists in 7.9-RC1 release. It is not just hc endpoint but also other /api endpoints giving 403(which is also strange because in the call no credentials(401!) specified. ). On the other hand, in earlier versions this was not the case 

FF: 7.9-20230811.190015

![image](https://github.com/ibissource/iaf/assets/10929856/71e2666f-6e98-4e45-aa0d-ecbbdb39a415)

FF: 7.9-RC1

![image](https://github.com/ibissource/iaf/assets/10929856/2f688f97-7e21-4789-b520-fb9fd2ca1071)
