### ISSUE TITLE
Backport frontend changes once the codebase is copied over to the 8.0 branch

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#5690]
**Describe the issue**
I've made a (minor) frontend change in #5525. Once the codebase is copied over to the 8.0 branch we need to make sure to merge my change into the new codebase.

The new base should be the backport of #4049 and #1980, on which the intermediate changes specified in https://github.com/frankframework/frankframework/issues/5690#issuecomment-1850447644 should be applied.

**Reporter**
Niels

**Comment by Matthbo** [comment]
Commits that may not have been accounted for since 7.9 new console development, from oldest to newest:
- [ ]  https://github.com/frankframework/frankframework/commit/3b017cd538710f5e71e6cbdf7e0a8defb8559313
- [ ]  https://github.com/frankframework/frankframework/commit/84dbdbeec31caf2df09f53abcf514e5269da3639
- [ ]  https://github.com/frankframework/frankframework/commit/f9ab14d2d436846d86f9f7904df4e189078d8f9c
- [ ]  https://github.com/frankframework/frankframework/commit/0d874bbb517a8cd072b44d8fd7c9fa9d1748d12f
- [ ]  https://github.com/frankframework/frankframework/commit/3649b8af7191dc646a49b5407ae3185bf456b86d
