### ISSUE TITLE
(7.9.0) EsbJmsListener is not able to read bytesMessage that is provided by EsbJmsSender

### ISSUE THREAD

**Issue by alisihab** [frankframework/frankframework#6048]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Have an adapter getting http req. and forwarding to a queue. Another adapter listening to the queue picks up the message and says it is empty although the body was provided from the first adapter(probably as bytes message).

**Reporter**
Ali

Resources will be provided

**Comment by tnleeuw** [comment]
What is the exact build of the framework that you are using?

Does the message need to be sent out as bytesMessage? Is it explicitly defined that way in the sender?

**Comment by alisihab** [comment]
We use the 7.9.0 release. There is no explicit setting to use bytesMessage anywhere. 

These answers could also be found in the resources that were provided

Let me know if you need anything else

**Comment by tnleeuw** [comment]
Sorry I did not have time yet to look at those!

If you do not need bytes messages, does it help to set defaultMessageClass to "TEXT" and also explicitly set the messageClass of the sender to "TEXT"?

Again sorry if this is already in the provided resources but have not yet had a chance to look at them.

**Comment by alisihab** [comment]
This was blocking business testing, the ff upgrade is reverted. I can try that later if there is no fix in the framework.

**Comment by tnleeuw** [comment]
I need to investigate the issue; we should have some test scenarios with senders and listeners that use bytesMessages and they work so I was hoping that by forcing everything to text-messages we could narrow down investigation.

**Comment by tnleeuw** [comment]
I don't yet understand why the message is sent as a BytesMessage but the bug is indeed related to receiving the message as a BytesMessage, in an EsbJmsListener.

Inspecting the code it appears that in this case the message is read twice, but after the first time reading the message is not reset to the beginning.

Therefore in the pipeline, the message appears to be empty.

The code to read the message also has some bugs under some circumstances, but that is not releated to the specific issue here.
