### ISSUE TITLE
Log download broken

### ISSUE THREAD

**Issue by jacodg** [frankframework/frankframework#6447]
**Describe the issue**
When I use Download at https://frank2example.frankframework.org/iaf/gui/#/logging for frank2example.log a new tab opens which shows the following:

![image](https://github.com/frankframework/frankframework/assets/2970084/ff6f1108-d506-4253-a2df-38e9ccf63cf2)

Instead of a new tab being opened the file should be downloaded.

**Additional Environment**
 - Browser: Chrome and Firefox

**Comment by Matthbo** [comment]
Download button used to open a new tab to the file-viewer api endpoint where the browser would request with the right Accept header. For some reason this doesn't happen anymore because it requests everything as 'text/html'.

Maybe let angular download it and decide the right content type based on file extension defined at the end of the filename, this will probably cause issues for big files.
