### ISSUE TITLE
Cannot create a FileSystemPipe to delete directory that does not yet exist

### ISSUE THREAD

**Issue by tnleeuw** [frankframework/frankframework#6597]
**Describe the issue**
When defining a pipe like this, the system gives an error on starting this pipe in the pipeline when the given directory `${testdata.dir}/mfp/` does not exist at that time:

```xml
			<LocalFileSystemPipe
				name="delete dir"
				action="rmdir"
				removeNonEmptyFolder="true"
				inputFolder="${testdata.dir}/mfp/"
			/>

```

As a workaround, you can specify the attribute `createFolder="true"`:
```xml
			<LocalFileSystemPipe
				name="delete dir"
				action="rmdir"
				removeNonEmptyFolder="true"
				createFolder="true"
				inputFolder="${testdata.dir}/mfp/"
			/>

```

Which is of course odd -- create a directory to remove it.

**Reporter**
Tim van der Leeuw

**Comment by Laurens-makel** [comment]
Bit similair, but not exactly the same:

Whenever I use a `FileSystemPipe` with action `mkdir` and the directory already exists when the pipe is executed, a `PipeRunException` is returned stating that the directory cannot be created because it already exists.

In this case I'd expect similair behaviour to the `mkdir` command on Unix systems, which also does not return with exit code 1 when a directory already exists.

**Comment by tnleeuw** [comment]
> Bit similair, but not exactly the same:
> 
> Whenever I use a `FileSystemPipe` with action `mkdir` and the directory already exists when the pipe is executed, a `PipeRunException` is returned stating that the directory cannot be created because it already exists.
> 
> In this case I'd expect similair behaviour to the `mkdir` command on Unix systems, which also does not return with exit code 1 when a directory already exists.

Also similar to your scenario, is that `rmdir` on a directory that does not exist also throws an exception. So even fixing the issue that you cannot start the pipe, throwing when the directory not exist is another problem.

See also: https://github.com/frankframework/frankframework/issues/4933
