### ISSUE TITLE
Param with pattern="{now}" and type="DATE" results in DATETIME instead

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#6693]
**❗ please do not add sensitive information in issues, you can provide extra information via email using issue number as reference ❗**

**Describe the issue**
Param with pattern="{now}" and type="DATE" results in DATETIME instead. Only difference from type="DATETIME" is that the time part is set to 00:00:00Z when using type="DATE".

**Reporter**
M. Lenterman

**To Reproduce**

**Screenshots**

**Configuration**
```
<Param name="NowDate" pattern="{now}" type="DATE" />
```

**Input**
```
Please provide an example of the input message. 
Alternatively, provide a Ladybug report.
```

**Environment**
```
FF! 8.1.0-RC2-20240411.160355: Openforms2bpel 1.16.4
Running on c3233bd5b6ad using Apache Tomcat/9.0.87
Java Version: OpenJDK Runtime Environment (17.0.10+7)
Heap size: 231M, total JVM memory: 360M
Free disk space: 181GB, total disk space: 251GB
Up since: 2024-04-18 15:53:54 (4m) 
```

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by nielsm5** [comment]
We now have a DateParameter which should make this problem a bit easier to tackle.
From JdbcUtil:
```
	case DATE:
		return JDBCType.DATE;
	case TIMESTAMP:
	case DATETIME:
	case XMLDATETIME:
		return JDBCType.TIMESTAMP;
	case TIME:
		return JDBCType.TIME;
```
A distinct difference should be made between these 5 types.

**Comment by thomaspj10** [comment]
The formatType attribute of a DateParam specifies how the input string (in this case the current datetime) should be parsed into a Date object. This is `yyyy-MM-dd` when you specify the formatType as `DATE`. This conversion yields a Date object with `yyyy-MM-dd 00:00:00`, because the time format was not specified. It however does not affect the conversion of a Date object back to a String (when you return it with a FixedResultPipe). It simply calls `toString()` on it causing this incorrectly formatted String.
