### ISSUE TITLE
Sending e-mails using MS Graph Entra Id

### ISSUE THREAD

**Issue by RayetSena** [frankframework/frankframework#6750]
![image](https://github.com/frankframework/frankframework/assets/55273803/38091b9f-a7b3-419f-bced-a72a6e28111d)

Can you add a feature to send emails using MS Graph Entra Id or do you have any suggestions for this?

**Reporter**
Sena

**Comment by jacodg** [comment]
Should be possible with ExchangeFileSystem

**Comment by Laurens-makel** [comment]
> Should be possible with ExchangeFileSystem

Nope, these API's are entirely different and Microsoft recommends to move away from EWS towards MS Graph API.... 
https://learn.microsoft.com/en-us/graph/migrate-exchange-web-services-overview

**Comment by tnleeuw** [comment]
The ExchangeFileSystem should however still work with Exchange Online and OAuth2 instead of using SMTP, as far as I know.
So this should allow sending of mails via Exchange Online and in future when in the framework we rewrite the ExchangeFileSystem to use the new MS Graph API, this can hopefully be upgraded with little or no change to the adapter configurations.

**Comment by Laurens-makel** [comment]
The business question seems to be sending e-mails using MS Graph, the given answer is you can use EWS for this. Without providing that EWS is deprecated and will be stopped in 2026..

From a framework perspective it's a simple change to change the listener type once the relevant MS Graph listener has been created, however it could be much more work organisational wise to make this change happen. Processes has been created, authorization have been granted, firewall changes are made proxy configurations are made, all based on a deprecated API. Depending on the complexity of the organisation, it might be a painful process to change from EWS to MS Graph.

In my opinion, it's wrong to advice to use a deprecated API without providing additional warnings.

**Comment by nielsm5** [comment]
Due to the complexity and severe lack of tests for the ExchangeFileSystem we think that the technical change will take quite some time. The reason this is being pushed back it because there are other priorities, right now LCM of certain dependencies is a big one, as this has a 2 month deadline. The stability of the framework for all outweighs this functionality for a few and thus we constantly try to prioritize our issues to keep everyone happy, but I hope you can also understand that this is a tough and time consuming task.

**Comment by Laurens-makel** [comment]
If the business case is only sending mails through ms graph, then an advice could also be to do this with the HttpSender and implement it according the following docs for the time being:
https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http

Yes, once the desired components are there, the Frank developer has to change their configuration, however no process, authorization, firewall or proxy changes required.

**Comment by RayetSena** [comment]
Used HttpSender for sending mails through MSGraph.

**Comment by evandongen** [comment]
@RayetSena , can you provide the solution you implemented? We still need to fix this in the framework but before that's done we'd like to have a workaround documented somewhere

**Comment by RayetSena** [comment]
Hey, @evandongen sorry for the delay, I can share an example of how to use this. First, you can check https://learn.microsoft.com/en-us/graph/auth/auth-concepts. 
![image](https://github.com/user-attachments/assets/b5f03a55-b860-4483-a1e1-7f0b8003144f)
![image](https://github.com/user-attachments/assets/661ca542-041c-47ad-b795-58418ce2fef4)
This is an example of how to get the token.

![image](https://github.com/user-attachments/assets/d5891be8-7d52-45e8-bfe3-69dcdc16155f)
This is an example of sending an email. 

I hope this helps, let me know if you need more information.
