### ISSUE TITLE
Make Larva tests run in parallel

### ISSUE THREAD

**Issue by jkosternl** [frankframework/frankframework#7041]
### Related Problem or Business Case

Larva tests take long time to run

### Describe the Feature

Currently, all Larva tests are ran sequentially. This takes quite some time, while the tests itself consists of many delays and waiting for response actions. This can be speed up, by executing tests in parallel. 

### Collaboration with External Companies

No, community resolution only

**Comment by Laurens-makel** [comment]
Most Larva scenarios involve asserting database table state as well, when scenarios are run in parallel, the database state is very hard to assert.

Could you include an option to include/exclude tests for running in parallel?

**Comment by Laurens-makel** [comment]
Great to hear that it's not mandatory to run everything in parallel.

Have you thought about the idea of test groups, each groups would be a logical isolation of tests that cannot run parallel, thus must be executed sequentially however different groups could run parallel to each other?

**Comment by jkosternl** [comment]
> Have you thought about the idea of test groups, each group would be a logical isolation of tests that cannot run parallel, thus must be executed sequentially however different groups could run parallel to each other?

Hi @Laurens-makel, no I did not think about that. I think every directory of Larva-tests should be able to run in parallel with other tests and that those tests should be written as independent as possible. Since this multi threaded run option is soon available, this problem newly arises. Perhaps some tests need some changes to make them run well. 

This is also just a first iteration to introduce this feature. Also other problems showed up: Larva-tests with MS SQL (without Narayana) are having transaction issues, while other databases are doing fine. That should also probably be investigated by the Core team.

**Comment by Laurens-makel** [comment]
> I think every directory of Larva-tests should be able to run in parallel with other tests and that those tests should be written as independent as possible.

Usually scenarios in a sub directory test a functional flow, which is handled by 1-N adapters.

When testing a flow, the following tests are usually present:
- Happy flow, assert that records in database produced.
- Unhappy flow, assert that no records in database produced.

For my use cases, it's not going to be possible to have all scenarios in a directory be run in parallel because of this. I'd have to blacklist all the directories that contain JDBC related tests.. Since many applications are heavily reliant on a database and it's state, the current implantation of this feature is not applicable to that much applications.

Re-writing existing tests is possible (to a certain extend) but a LOT of work, to make it work, each test should only interact with it's own dataset by specifically operating on ID's related to the test case. This would heavily reduce the maintainability of tests files. 

I completely understand that this is a first draft however with the suggestion of using test groups, each directory is still executed sequentially however the several directories could be executed in parallel. It would give the intended boost to test execution speed of Larva to JDBC heavy applications, without putting a huge burden on the Frank developer to rewrite existing tests..

**Comment by jkosternl** [comment]
> I completely understand that this is a first draft however with the suggestion of using test groups, each scenario within a directory is still executed sequentially however the several directories could be executed in parallel. It would give the intended boost to test execution speed of Larva to JDBC heavy applications, without putting a huge burden on the Frank developer to rewrite existing tests..

Hi @Laurens-makel, the current implementation does not require you to put all in the same directory. It splits all Larva scenarios by the subfolder of the root directory. So, in case of the basic Docker image of FF, all scenario's and subdirectories of `ApiListener` will be executed by the same worker.

I hope this PR gets merged soon into a `8.2-SNAPSHOT` release and you can really use it in your dev/test environment, to figure out some real results. Feel free to raise a new improvement issue, based upon your first experience. Your ideas really make sense, I can understand. 
FYI: Improving the Larva speed is never raised as a request, as far as I know. This whole issue is my own initiative.

**Comment by nielsm5** [comment]
I think @jkosternl assumes that each folder is a standalone operation/function within the application? However in reality almost every scenario will require the database, will means it won't be able to run in parallel. Only when stubbing the database, or using a new test database for each test this could be accomplished.

**Comment by jkosternl** [comment]
> I think @jkosternl assumes...

This is just a first attempt to move to parallelization of execution. For the current Larva set as the default FF has, this works pretty well. For instances in the wild, perhaps new ideas will arise, as what Laurens commented. So, future improvements are always welcome right, and it is never too late for a good first step. It is still an optional feature, so let's continue.

**Comment by nielsm5** [comment]
Oh definitely. You have to start somewhere. Now we need to figure out how to continue from here!
