### ISSUE TITLE
MessageType in FileSystemListener schould be a enum (and contents should be content)

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#7219]
### Current Behavior

The documentation of the directory listener is not very clear

### Expected Behavior

Possible improvements
- Make the message Type an enum instead of a string.
- The name MessageType is not very descriptive for what it does. 
- The meaning of content and contents is very clos to each other but in my opinion it should be content of filecontent
- example in the frankdoc would be welcome
### Environment Information

ff 8.2.0

### Steps To Reproduce

https://frankdoc.frankframework.org/#/Listeners/DirectoryListener

**Comment by thomaspj10** [comment]
Making the `messageType`  an enum is not really an option due to two reasons. First of all, this attribute also serves as a key to search for a header in an email (for ImapListener) or an attribute in a file (for DirectoryListener). Second of all the enum would have to be used for both directory based listeners and email based listeners, due to their shared implementation. This would make the possible values even more confusing in my opinion.

I have thought of a different name for `messageType`, but I couldn't really come up with another good name. Do you have any suggestions?

I do not understand the third point. Can you elaborate?

I have improved the documentation as suggested.
