### ISSUE TITLE
Directory listener does not want to retry a message from the error store and Filetimesensitive add timestamp in strange place

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frankframework#7242]
### Current Behavior

I forced an error in my csv file to test the resend mechanism of the directory listener

**The FileTimeSenitive adds the timestamp in the filetype suffix (my file no longer matches the file pattern** 

**When retrying the message from the console I get the following error.**
Unable to resend message [access-code-password-recovery-code - ERROR - Copy.csv-2024-08-05T07_41_07.922]. unable to retry message with id [access-code-password-recovery-code - ERROR - Copy.csv-2024-08-05T07_41_07.922]: Cannot change processState to [ERROR] for [access-code-password-recovery-code - ERROR - Copy.csv-2024-08-05T07_41_07.922]: Cannot move file to [access-code-password-recovery-code - ERROR - Copy.csv-2024-08-05T07_41_07.922]. Destination file [C:\temp\error\access-code-password-recovery-code - ERROR - Copy.csv-2024-08-05T07_41_07.922] already exists.

### Expected Behavior

filename: access-code-password-recovery-code - ERROR - Copy-2024-08-05T07_41_07.922.csv

Proper retry of the message instead of an error (I expect the file to be moved to the input and end up in the error folder.

### Environment Information

FF! 8.3.0-20240730.042429: Partner-Developer

### Configuration

```xml
<Module	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="../FrankConfig.xsd">

	<Adapter name="processfile">
		<Receiver name="processfile">
			<DirectoryListener 
				inputFolder="c:\temp\input" 
				inProcessFolder="c:\temp\inprocess" 
				processedFolder="c:\temp\processed" 
				errorFolder="c:\temp\error"
				wildcard="*.csv"
				createFolders="true"
				fileTimeSensitive="true"
				messageType="contents"/>
		</Receiver>

		<Pipeline>
			<Exits>
				<Exit name="READY" state="SUCCESS"  />

			</Exits>
			<CsvParserPipe name="parsecsv" fieldSeparator=";" prettyPrint="true"/>			
			
		</Pipeline>
	</Adapter>

</Module>
```

### Input

[access-code-password-recovery-code - ERROR.csv](https://github.com/user-attachments/files/16491290/access-code-password-recovery-code.-.ERROR.csv)

**Comment by tnleeuw** [comment]
Actually the DirectoryListener does want to retry to message -- but the message has again an error, and then the DirectoryListener fails to move the file into the errorstorage again since it was never removed from there.

I think that until a fix is merged, this might be worked around by setting `numberOfBackups` to a non-zero value.

I'm now changing the code to move the file from the error-storage to in-process when it is being retried. However, that depends on there being an "In Process" folder configured.

The changing of the extension in combination with the wildcard makes it so that moving the message to "Available" status again will not have the desired effect. I'm changing the code to preserve the file extension, however it is possible to come up with wildcards that will still not work in combination with the filename-changes done when `fileTimeSensitive` is set. So this is a patch on the problem but not a full fix.
