### ISSUE TITLE
Tibco age field may not be negative

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#7266]
### Current Behavior

Tibco age field may not be negative

### Expected Behavior

Tibco age field may not be negative

### Environment Information

Tibco age field may not be negative

### Steps To Reproduce

Tibco age field may not be negative

### Configuration

Tibco age field may not be negative

### Input

Tibco age field may not be negative

### What database are you using?

Tibco age field may not be negative

### What browsers are you seeing the problem on?

Tibco age field may not be negative

### Relevant Log Output

Tibco age field may not be negative

### Anything else?

Tibco age field may not be negative

**Comment by philipsens** [comment]
### Current Behavior

Shit goes bad when Tibco get a negative value.

### Expected Behavior

Trow an exception when value is negative.

### Environment Information

8.2 ...

### Steps To Reproduce

Run a pipeline

### Configuration

<xml />

### Input

-1

### What database are you using?

-

### What browsers are you seeing the problem on?

-

### Relevant Log Output

```console
Stacktrace
```

### Anything else?

I'm using Tibco FF
