### ISSUE TITLE
frankdoc not loading locally

### ISSUE THREAD

**Issue by VBPham** [frankframework/frankframework#7424]
### Current Behavior

frankdoc page is stuck on loading when accessing it via locally started frank

### Expected Behavior

frankdoc opening normally

### Environment Information

**FF! 8.3.0-20240828.042324**: Frank2D 
Running on **[Redacted]** using **Apache Tomcat/10.1.25**
Java Version: **OpenJDK Runtime Environment (21.0.4)**
Heap size: **160.9 MiB**, total JVM memory: **336.0 MiB**
Free memory: **175.1 MiB**, max memory: **4.0 GiB**
Free disk space: **97.5 GiB**, total disk space: **465.6 GiB**

### Steps To Reproduce

1. start frank
2. go to frankdoc
3. no profit

### What browsers are you seeing the problem on?

Firefox

### Anything else?

maybe relevant devtools output

![image](https://github.com/user-attachments/assets/bb3ed097-f28b-48ef-b8dd-2091cce571f2)

**Comment by Matthbo** [comment]
@thomaspj10 also had this issue yesterday
After a quick bit of research it seems that the frankdoc url `/iaf/frankdoc` is being loaded by the `ConsoleFrontend` servlet instead of the correct handlers.
The console frontend can't find the right resources (because the path is not matching for it) and so it shows the 'Loading' text without being able to do anything after
