### ISSUE TITLE
Attributes on Params missing/not working in FrankConfig.xsd

### ISSUE THREAD

**Issue by MLenterman** [frankframework/frankframework#7682]
### Current Behavior

Attributes on Params missing/not working correctly in FrankConfig.xsd. Code completion via schema no longer works for them.

### Expected Behavior

.

### Environment Information

FF! 8.3.0-20241010.042329: ZaakBrug 1.22.0
Running on a2999fdb1b44 using Apache Tomcat/10.1.28
Java Version: OpenJDK Runtime Environment (21.0.4+7-LTS)
Heap size: 365.8 MiB, total JVM memory: 864.0 MiB
Free memory: 498.2 MiB, max memory: 11.7 GiB
Free disk space: 164.5 GiB, total disk space: 250.9 GiB
Up since: 2024-10-14 10:19:30 (4h)

**Comment by nielsm5** [comment]
We're trying to encourage people to use the specific Parameter implementations, so it's possible some attributes are disappearing from the 'old school' parameter element.

**Comment by nielsm5** [comment]
Not sure why this is happening, the json looks fine and the attributes are also in the XSD?

**Comment by thomaspj10** [comment]
The problem indeed happens, due to the interface `IParameter`, which `Parameter` inherits from. The name is the same, so it breaks for `Parameter`, but not for `BooleanParameter` for example, which is dumb.

**Comment by thomaspj10** [comment]
I have also found a bug that `NumberParam`, `BooleanParam` and `DateParam` couldn't be used in `ErrorMessageFormatter`.

**Comment by thomaspj10** [comment]
Attributes are not defined and a generic Param element is generated, so the Frank!Doc stays compatible the old way (i.e. `className=""`). It adds `anyAttribute` in the XSD, because it should support all parameters which fall under the `IParameter` interface. It does detect the name conflict between the generic Param (IParameter) and the concrete param (Parameter), but the code decided to exclude concrete param, because an element with a duplicate name is ofcource not possible.

A potential solution could be to add the attributes of the concrete param to the abstract param, so a developer has a bit of type safety, but that is more of a band aid then a proper solution, because the anyAttributes is still required for backwards compatibility.
