### ISSUE TITLE
digester cleanup tasks

### ISSUE THREAD

**Issue by nielsm5** [frankframework/frankframework#7725]
- [x] Remove selfRegisterMethod
- [x] See what we can do with registerTextMethod
- [x] Remove all register methods, because I forgot some :(
- [:(] `SenderSeries#setSender` may be removed?

**Comment by thomaspj10** [comment]
Removing `SenderSeries#setSender` sadly doesn't seem to be possible due to the two lines in the digester-rules.xml

```xml
	<rule pattern="*/sender" registerMethod="setSender" beanClass="org.frankframework.core.ISender" />
	<rule pattern="*/sender" registerMethod="addSender" beanClass="org.frankframework.core.ISender" />
```

`SenderWrapper` may only contain 1 sender, while a `SenderSeries` or `ParallelSenders` can contain multiple. The pattern doesn't allow me too differentiate between those use-cases, so I must make it be able to handle both.
